// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzD-UdNRYrdtjk5MNbAfhqzmOxxFIhK8I',
    appId: '1:211558308047:web:efee33b230be10fa5f7fba',
    messagingSenderId: '211558308047',
    projectId: 'al-ridha-a22da',
    authDomain: 'al-ridha-a22da.firebaseapp.com',
    storageBucket: 'al-ridha-a22da.appspot.com',
    measurementId: 'G-EVJ9PTT7N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJE6BUTwfgRMK2G1IsqM5TrIU9hmafZGk',
    appId: '1:211558308047:android:4e5f21fc53bd2dde5f7fba',
    messagingSenderId: '211558308047',
    projectId: 'al-ridha-a22da',
    storageBucket: 'al-ridha-a22da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ueKi6vIEPMaIspKLdw0qv7sj1gHRes0',
    appId: '1:211558308047:ios:8620b529505f57415f7fba',
    messagingSenderId: '211558308047',
    projectId: 'al-ridha-a22da',
    storageBucket: 'al-ridha-a22da.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ueKi6vIEPMaIspKLdw0qv7sj1gHRes0',
    appId: '1:211558308047:ios:fd9a61b7265848d65f7fba',
    messagingSenderId: '211558308047',
    projectId: 'al-ridha-a22da',
    storageBucket: 'al-ridha-a22da.appspot.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
